### PR TITLE
Update group configuration

### PR DESCRIPTION
**Pull request by olafveerman**
Add new groups.
Remove description on request of the content team.

Fix nasa-impact/covid-dashboard#198

### CODE REVIEW

**Comment by olafveerman** [comment]
To make tests pass, should I remove the `prose: null`?

**Comment by vincentsarago** [comment]
@olafveerman looking at the model, prose has to be a string https://github.com/NASA-IMPACT/covid-api/blob/master/covid_api/models/static.py#L87 
if `prose` is not really used we can remove it from the model maybe cc @drewbo

**Comment by olafveerman** [comment]
@vincentsarago Is this a good solution? I made prose optional, and thereby nullable.

**Comment by vincentsarago** [comment]
they will still be returned in the API response, but this can be handled in the Frontend I guess

**Pull request merged**
