### PR TITLE
Release v0.3.2

### PR DESCRIPTION
**Pull request by olafveerman**
# Changelog

## :bug: Fixes

* use the correct `raster-opacity` property - NASA-IMPACT/covid-dashboard#482
* load the XCO2 base data from the correct S3 path
* use the correct color map for Nightlights VIIRS - NASA-IMPACT/covid-dashboard#473

### CODE REVIEW

**Review by leothomas — APPROVED** [review]
Looks good to me. I thought I had already changed the S3 path of the `xco2-base` dataset, but I might be wrong. 

I ran `aws s3 sync --dryrun` on `xco2/xc02_16day_base.*` and `xco2-base/` to ensure nothing was missing. 

I also built and ran the API to ensure that the `/datasets` endpoint correctly returns `raster-opacity` (as opposed to `raster_opacity`). 

image

**Comment by olafveerman** [comment]
Awesome, thanks @leothomas 

Just noticed that the screenshot of your response has an opacity of `0`, while the config has `0.9`

**Comment by leothomas** [comment]
Hm, that sounds like an int to float cast somewhere. Checking now

**Comment by leothomas** [comment]
The `Paint` pydantic model indeed had `raster_opacity` was defined as `int`. I've just updated it to float

**Comment by leothomas** [comment]
image

**Comment by leothomas** [comment]
image

**Comment by olafveerman** [comment]
Thanks @leothomas!

**Pull request merged**
